### ISSUE TITLE
Android调用RNShortVideo.recordShortVideo后，APP奔溃了

### ISSUE THREAD

**Issue by iUUCoder** [xinlc/react-native-aliyun-video#2]
Android 9.0系统中，第一次调用`RNShortVideo.recordShortVideo`，正常请求了设备权限，然后就没有反应了，再次调用`RNShortVideo.recordShortVideo`，APP就奔溃了。

- Android Studio 3.2
- Gradle Version 4.4

Module: app

```
...
android {
    ...
    packagingOptions {
        pickFirst "**/libgnustl_shared.so"
    }
    ...
}

repositories {
    flatDir {
        dirs 'libs', '$rootDir/../../../node_modules/react-native-aliyun-short-video/android/libs'
    }
}

dependencies {
    implementation project(':react-native-aliyun-short-video')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}
...
```

Module: react-native-aliyun-short-video

```
...
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.facebook.react:react-native:+'

    implementation(name: 'QuSdk-RC', ext: 'aar')
    implementation 'com.android.support:appcompat-v7:24.2.1'
    implementation 'com.android.support:design:24.2.1'
    implementation 'com.google.code.findbugs:jsr305:3.0.0'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'pub.devrel:easypermissions:0.2.1'
    implementation 'com.squareup.okhttp3:okhttp:3.2.0'
    implementation 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
    implementation 'com.squareup.okio:okio:1.12.0'
    implementation 'com.google.code.gson:gson:2.8.0'

    implementation(name: 'AlivcPlayer-3.4.6', ext: 'aar')
    implementation(name: 'AlivcReporter-1.2', ext: 'aar')
    implementation(name: 'AliyunVodPlayer-3.4.6', ext: 'aar')

    implementation 'com.aliyun.dpa:oss-android-sdk:+'
}
...
```

错误信息：

```
...
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zsyz.test, PID: 9332
    java.lang.NoSuchFieldError: No static field abc_action_bar_view_list_nav_layout of type I in class Lcom/aliyun/snap/snap_core/R$layout; or its superclasses (declaration of 'com.aliyun.snap.snap_core.R$layout' appears in /data/app/com.zsyz-MeUgaolTl3tjo68gMRfiGQ==/split_lib_slice_4_apk.apk)
        at com.aliyun.demo.R$layout.<clinit>(R.java:1130)
        at com.aliyun.demo.recorder.AliyunVideoRecorder.onCreate(SourceFile:143)
        at android.app.Activity.performCreate(Activity.java:7200)
        at android.app.Activity.performCreate(Activity.java:7191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
...
```

**Comment by xinlc** [comment]
@iUUCoder 运行Example是否会崩溃？

**Comment by iUUCoder** [comment]
> @iUUCoder 运行Example是否会崩溃？

Example没有问题，应该是Android Gradled版本的问题，我把RN 降到0.55.4就行了。
后期大佬可以考虑一下支持RN@^0.57.0，感谢大佬！
